### PR TITLE
Remove deprecated function

### PR DESCRIPTION
**Pull request by mjwen**
This removes several deprecated functions and arguments from molecule entry as discussed in #9.

~~P.S. I used to format these files using black with a line length of 88, but now changed to 100. Most of the changes in the file are just formatting. I can create another PR to format all our code before merging this. Moving forward, we'd better format the same way (I know most of us are using black now, but we still does not use the same length). @shyamd you may want to decide it.~~ 
Blacked formatted with --line--length 100 in #35. Please merge that first.

### CODE REVIEW

**Comment by espottesmith** [comment]
Just merged in #35. Fix conflicts (ought to be easy), push again, and I'll merge this in. Sorry this has taken so long!

**Comment by mjwen** [comment]
@espottesmith should be good now... It's still failing the black lint check since the current GH Action setting requires a line length of 88. I am still working on finding a way to set it to 100.

**Comment by mjwen** [comment]
@espottesmith probably should be good for now?  It's still failing many mypy type hint checks. I took a look at some of them and it seems mypy is too aggressive and not as smart as it should be. For example, when some function argument is set to `None` as a default and reset in the function, mypy will not respect the reset and report an error if accessing an attribute of the argument.

**Comment by espottesmith** [comment]
It seems like we could avoid that issue - for instance, just making a new variable name within the function - but if that's all that's failing, I'm fine merging in for now.

**Pull request merged**
